#!/bin/bash

# ANSIcolor -- Use these variables to make output in different colors
#   and formats. Color names that end with 'f' are foregorunds colors,
#   and those ending with 'b' are background colors.

ANSIcolors()
{
    esc="\e" #If doesn't work, enter an ESC directly

    # Foreground colors
    blackf="${esc}[30m";    yellowf="${esc}[33m"    cyanf="${esc}[36m";
    redf="${esc}[31m";      bluef="${esc}[34m";     whitef="${esc}[37m"
    greenf="${esc}[32m"     purplef="${esc}[35m"

    # Background colors
    blackb="${esc}[40m";    yellowb="${esc}[43m"    cyanb="${esc}[46m";
    redb="${esc}[41m";      blueb="${esc}[44m";     whiteb="${esc}[47m"
    greenb="${esc}[42m"     purpleb="${esc}[45m"    

    # Bold, italic, underline, and inverse style toggles
    boldon="${esc}[1m";     boldoff="${esc}[22m"    italicson="${esc}[3m"; 
    italicsoff="${esc}[23m" ulon="${esc}[4m";       uloff="${esc}[24m"
    invon="${esc}[7m";      invoff="${esc}[27m"

    reset="${esc}[0m"
}

ANSIcolors


echo -e "${yellowf}This is a phrase in yellow${redb} and red${reset}"
echo -e "${boldon}This is bold${ulon} this is italics${reset} bye-bye"
echo -e "${italicson}This is italics${italicsoff} and this is not"
echo -e "${ulon}This is ul${uloff} and this is not"
echo -e "${invon}This is inv${invoff} and this is not"
echo -e "${yellowf}${redb}Warning I ${yellowb}${redf}Warning II${reset}"

