#!/bin/bash 

# logrm -- Logs all files deletetion requests unless the -s flag is used
#   need the removelog directory, and the permissions

removelog="/var/log/remove.log"

if [ $# -eq 0 ] ; then
    echo "Usage: $(basename $0) [-s] list of files or diectories" >&2
    exit 1
fi

if [ "$1" = "-s" ] ; then
    # Silent operation requested ... don't log.
    shift
else
    echo "$(date): ${USER}: $@" >> $removelog
fi

/bin/rm "$@"

exit 0
